name: ci1stlab
on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: doewnload code
        uses: actions/chekout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
